### PR TITLE
Don't ignore --config-file when using --stdin

### LINKED ISSUE #230: `--config-file` is ignored when using `--stdin`
**Describe the bug**

`--config-file` is ignored when using `--stdin`

**To Reproduce**

```
cd /tmp
mkdir foo bar

cd foo
treefmt --init
[INFO]: Generated treefmt template at /tmp/foo/treefmt.toml

cd ../bar
treefmt --config-file ../foo/treefmt.toml --tree-root .
[ERR]: Failed to load formatter #mylanguage due to error: cannot find binary path
[ERR]: One or more formatters are missing

cat /dev/null | treefmt --config-file ../foo/treefmt.toml --tree-root . --stdin x
[ERR]: treefmt.toml could not be found in /tmp/bar and up. Use the --init option to create one.
```

**Expected behavior**

The second invocation of `treefmt` above should give:

```
[ERROR] Ignoring formatter #mylanguage due to error: could not find 'command-to-run' on PATH
```

**System information**

```
$ uname -a
Linux io 6.2.8 #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar 22 12:38:11 UTC 2023 x86_64 GNU/Linux

$ treefmt --version
treefmt 0.5.0
```

**Additional context**

### PR DESCRIPTION
**Pull request by lbodor**
Fix #230.

### CODE REVIEW

File: src/command/format_stdin.rs [hunk 1]
```diff
@@ -21,18 +22,6 @@ pub fn format_stdin_cmd(
         }
     };
 
-    // Search for the treefmt.toml from there.
-    let config_file = match config::lookup(work_dir) {
```
Comment (lbodor) [inline src/command/format_stdin.rs:25]: Doesn't `config::lookup()` already happen in `cli_from_args()` for both `format_cmd()` and `format_stdin_cmd()`?

File: src/command/format_stdin.rs [hunk 2]
```diff
@@ -21,18 +22,6 @@ pub fn format_stdin_cmd(
...
-        Some(path) => path,
-        None => {
-            return Err(anyhow!(
-                "{} could not be found in {} and up. Use the --init option to create one.",
-                config::FILENAME,
-                work_dir.display()
-            ));
-        }
```
Comment (lbodor) [inline src/command/format_stdin.rs:33]: This check is in `run_cli()` and now also applies to both `format_cmd()` and `format_stdin_cmd()`.

File: src/command/mod.rs [hunk 3]
```diff
@@ -119,32 +119,41 @@ pub fn cli_from_args() -> anyhow::Result<Cli> {
...
     } else {
-        // Fail if configuration could not be found. This is checked
-        // here to avoid aborting before init_cmd.
-        if cli.config_file.is_none() {
-            return Err(anyhow!(
-                "{} could not be found in {} and up. Use the --init option to create one or specify --config-file if it is in a non-standard location.",
-                config::FILENAME,
-                cli.work_dir.display(),
-            ));
+        match &cli.config_file {
```
Comment (lbodor) [inline src/command/mod.rs:123]: Let me know if you prefer `is_none()` followed by `expect()`, and I'll do that instead.

**Review by zimbatm — APPROVED** [review]
thanks! LGTM

borg merge

File: src/command/format_stdin.rs [hunk 4]
```diff
@@ -21,22 +22,10 @@ pub fn format_stdin_cmd(
...
-    };
-
     // Default the tree root to the folder that contains the config file
     let tree_root = tree_root.clone().unwrap_or_else(|| {
         // unwrap: since the config_file is a file, there MUST be a parent folder.
-        config_file.clone().parent().unwrap().to_path_buf()
+        config_file.parent().unwrap().to_path_buf()
```
Comment (lbodor) [inline src/command/format_stdin.rs:28]: Now same as

https://github.com/numtide/treefmt/blob/d87045a6f3f6b2cbf85e1ae1eb10d548dd51829a/src/command/format.rs#L30

resolves

https://github.com/numtide/treefmt/actions/runs/4649699136/jobs/8228370543

```
error: using `clone` on a double-reference; this will copy the reference of type `&std::path::Path` instead of cloning the inner type
  --> src/command/format_stdin.rs:28:9
   |
28 |         config_file.clone().parent().unwrap().to_path_buf()
```

File: src/command/mod.rs (hunk 3 above)
Comment (zimbatm) [reply src/command/mod.rs:123]: Both are fine by me

**Comment by zimbatm** [comment]
bors merge

**Comment by lbodor** [comment]
Thanks very much :ok_hand:
